### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by StFS**
*Issue #, if available:* #826

*Description of changes:* Update documentation for aws-apigateway-iot to clarify that the ATS endpoint must be used.

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: bd6a2aef073758ac9dd4a4aa0d736d60b0d42e32
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=47d86459-a0e7-4318-bfef-35c7d73793a7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by georgebearden** [comment]
Hi @StFS - Thank you for submitting this PR. Will you also please update the [comment on the property](https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/aws-apigateway-iot/lib/index.ts#L28) to match the wording you have in the README?

Once this PR is merged, the updated README contents should show up in the web docs in the next couple weeks as well.

**Comment by StFS** [comment]
@georgebearden done.

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: efdaf41477440e2e761815e5383fbdc9a2250d38
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c88e9b82-eed4-4d9f-b736-3d51d7776e05%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: ee5a3125242485733dfff27a37463505ed002166
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4312f5dd-aa10-4dbd-838c-d70f781fd723%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by georgebearden — APPROVED** [review]
lgtm

**Comment by georgebearden** [comment]
Thank you @StFS!

**Pull request merged**
