### PR TITLE
fix(npmlog): update npmlog version

### LINKED ISSUE #1074: Upgrade npmlog to higher version since npmlog: ^4.1.2 produce ReDoS vulnerabilties.
Description:
We ran a Synk scan on one of our repo and facing a vulnerability on "https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908"

On our research we identified that the root problem is aws-solutions-constructs -> core package is using npmlog version ^4.1.2
 [here](https://github.com/awslabs/aws-solutions-constructs/blob/5d5e0144c222ae9461ac9fc29fc983cb8953fea0/source/patterns/%40aws-solutions-constructs/core/package.json#L62) as dependencies which is causing the vulnerability.

We hit a similar issued earlier and we tried fixing it downstream by overriding the npmlog version to 7.0.1.  But this time we are not able to resolve the issue. Could you please help us to upgrade the npmlog and its dependencies to higher version ~7.0.1.

Thankyou!

**Error message from synk scan :** 
  Regular Expression Denial of Service (ReDoS) [High Severity][https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908] in ansi-regex@2.1.1
 introduced by @aws-solutions-constructs/core@2.46.0 > npmlog@4.1.2 > gauge@2.7.4 > string-width@1.0.2 > strip-ansi@3.0.1 > ansi-regex@2.1.1 and 1 other path(s)

### PR DESCRIPTION
**Pull request by biffgaut**
*Issue #, if available:*
Fixes #1074 

*Description of changes:*
Upgrades library version to address vulnerability discussed in Issue 1074

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 451fbbc952cc582421b484a495f513dd12415064
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a0c0f7c8-493d-497b-a111-647d22c99867%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 44a15cac2b00db71275b090230c460c86a3a5ae0
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d707930a-e17f-4818-bbd6-37719c83a1ad%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 2051d51d8f22c4265db19f97105c9b041ef91812
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f109a18a-7af9-41b4-9a96-2917ed30488e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 834bfe1c435c5bd41193dca2e0c4d39cc55d0621
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0e47fbfa-e4f6-46b2-bacb-8ee57fa724be%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 2070a73759793bbf88533b76de55bc3ce80a331d
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d3bc183f-9c54-45c4-b945-e1e462d3afb5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by hayesry — APPROVED** [review]

**Comment by jorgemaroto-eb** [comment]
@biffgaut when is expected to release a version which includes this change?

**Comment by biffgaut** [comment]
2.52.0 should be available now

**Pull request merged**
