### PR TITLE
fix(aws-apigateway-iot and aws-cloudfront-apigateway-lambda): fixed deprecated warnings

### LINKED ISSUE #551: Address the following Deprecation warning
PASS  test/test.apigateway-iot.test.js (7.958 s)
  ✓ Test for default Params construct props (126 ms)
  ✓ Test for default IAM Role (254 ms)
  ✓ Test for default Params request validator (144 ms)
  ✓ Test for default Params Integ Props and Method Props (128 ms)
  ✓ Test for valid iot enpoint (5 ms)
  ✓ Test for Binary Media types (126 ms)
  ✓ Test for Api Name and Desc (104 ms)
  ✓ Test for overriden IAM Role (103 ms)
  ✓ Test for APi Key Source (94 ms)
  ✓ Test for Api Key Creation (314 ms)
  ✓ Test for deployment ApiGateway AuthorizationType override (92 ms)
  ✓ Test for deployment ApiGateway AuthorizationType override (81 ms)
  ✓ Test for handling fully qualified iotEndpoint (138 ms)

  console.warn
    [WARNING] @aws-cdk/aws-apigateway.UsagePlanProps#apiKey is deprecated.
      use `addApiKey()`
      This API will be removed in the next majo

Also found in aws-cloudfront-apigateway-lambda

### PR DESCRIPTION
**Pull request by mickychetta**
*Issue #551 , if available:*

*Description of changes:*
-Replaces UsagePlanProp.apiKey with method addApiKey()
-options prop in LambdaRestApi has been deprecated since it now extends RestApiProps, removed options prop in test

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

fixes #551

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 0a7e0ff2abe730c02d76dea8d70fb765d33635ef
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8f3c96a1-ad97-4255-8fc4-8fbc1f9ed627%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 0a7e0ff2abe730c02d76dea8d70fb765d33635ef
* Result: FAILED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d60ee20c-d1bc-4f35-81e3-7ef5540af2ff%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: a5eaacf6b0193c421407d3a00132ea7547844d23
* Result: FAILED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5b046962-a6d5-4c69-84ab-287d4d23a6f7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: a5eaacf6b0193c421407d3a00132ea7547844d23
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=907256c7-6180-43ce-900c-ad7d81f5038a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 23e4ab8c6e29c4f18080aef03677a81284509c3f
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5b425fd5-8ea5-45e7-8fee-b461932fe528%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 23e4ab8c6e29c4f18080aef03677a81284509c3f
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1026057e-c1ba-4865-82e2-fe5bb7628757%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 9f4e139e99cb6f746a036a39c6d2b1c9e67f217d
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=39197b0d-38d0-4089-8f25-53634e03bb23%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 9f4e139e99cb6f746a036a39c6d2b1c9e67f217d
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=07b6bd52-d778-4d79-896b-4218b0ba1df1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by biffgaut — APPROVED** [review]

**Pull request merged**
