### PR TITLE
feat (Issue #61: aws-apigateway-iot construct update)

### PR DESCRIPTION
**Pull request by surukonda**
*Issue 61, if available:*

*Description of changes:* Updated the Architecture diagram and APIGateway IoT Integration Path for updating IoT thing named shadow documents

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: 1f355cf4d2a9a1da69b16efb3d2a956d20535f33
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3e10426b-6fc5-4673-9756-62a087433e08%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: ddb777408570b83d10f3171de6c02db1aa54bc8b
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=38d27ccf-7385-41ba-9f11-70f2a431266f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by biffgaut** [comment]
A couple questions-
* There's no discussion why make this change, what does it accomplish?
* Were the .expected.json files generated using cdk-integ?

Thanks

**Comment by surukonda** [comment]
- Hi @biffgaut . there are 2 different ways to update named shadows, the current implementation (in PR) is recommendation from service team.  From a functionality stand point there isn't any change that user of the construct would see. 

- *.expected.json files are created by cdk-integ.

**Comment by biffgaut** [comment]
Do we have any documentation on the proposed access method? I spoke to an IoT Specialist SA who was not aware of the proposed way and pointed me to docs showing the current access method - https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-mqtt.html

**Review by biffgaut — APPROVED** [review]
New URL format recommended by the service team: https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-rest-api.html

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: b00476591958136e8f1c4818517c181f3296ae67
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2a02bd75-9519-4efd-b6fd-d63e8f6707e2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
