### PR TITLE
feat(aws-sns-sqs): added sqsSubscriptionProps

### LINKED ISSUE #695: Add Raw Message Delivery parameter to aws-sns-sqs Module
Add a parameter to the aws-sns-sqs constructor to allow Raw Message Delivery to be toggled for the SNS Subscription that is created

### Use Case

I want Raw Message Delivery as an option so I can use SQS Filter Patterns more easily downstream as well as reduce the need to JSON de-serialize for lambda use cases, while also getting the convenience out of using this module (resource policies, KMS keys, etc.)

### Proposed Solution

Option 1: Add SqsSubscriptionProps to the constructor and pass it through to the SNS Subscription creation here: https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/aws-sns-sqs/lib/index.ts#L155

Option 2: Add rawMessageDelivery: bool to the constructor as a parameter, and pass through as an argument to a newly created  SqsSubscriptionProps at the same location as option 1: https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/aws-sns-sqs/lib/index.ts#L155

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by mickychetta**
*Issue #695 , if available:*

*Description of changes:*
- Added sqsSubscriptionProps to allow deadLetterQueue, filterPolicy, and rawMessageDelivery
- Created unit and integration tests to check DLQ, filter policy, and raw message delivery

*Notes:*
- sqsSubscriptionProps dead letter queue does not conflict with construct created SQS dead letter queue as they come from two different sources
  - **SNS DLQ**: Captures messages that can't be delivered to subscribers successfully
  - **SQS DLQ**: If a message can't be consumed successfully, it'll be sent to this dead-letter queue
- sqsSubscriptionProps is only applicable for this construct as it is for this very specific use case of SQS subscribing to SNS
- A possibility in the future is to implement lambdaSubscriptionProps for aws-sns-lambda
- If no override is provided in sqsSubscriptionProps, we stick to the CDK defaults: no DLQ, no filter policy (all messages are delivered), and `rawMessageDelivery: false`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

fixes #695

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: f07e90e15103e3146ca0e49aa3c14ca4a58f4990
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f1ae73d7-e241-437c-9c84-6ba03a83d702%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: f07e90e15103e3146ca0e49aa3c14ca4a58f4990
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7179a8b2-6ff5-4d99-9da3-7ee7b9774375%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 195c22450747cbcbb40d25349dffc051190e3930
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4a106c21-f9e4-4a9d-88a7-48f4e9850405%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 195c22450747cbcbb40d25349dffc051190e3930
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bf19e5ed-777b-48d0-b6f0-080a542e3c63%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by biffgaut — APPROVED** [review]

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 854f73d8bbd2a9756903b5edf49695374bf85075
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ad8cf310-fc0a-435b-83fb-c535836d275a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 854f73d8bbd2a9756903b5edf49695374bf85075
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=159b82ec-f641-4c30-ae65-3a84c6fb0b0e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
