### PR TITLE
chore(package.json): move proper packages to devDependencies

### PR DESCRIPTION
**Pull request by biffgaut**
Moving packages that are not distributed to devDependencies to remove them from package license reports.

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: afac559d7c29c2c1e593f16a4534199cb1a86f84
* Result: SUCCEEDED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=04901580-3fd1-4e7e-913a-d60ad0e3400a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 6058e8250bcaea6a2f8bc26684fd81b6c48792a9
* Result: SUCCEEDED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5531b455-cd73-4c6e-821d-ca66cd4095c6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 0b6456f682daab7203233606c63ed11815f4c205
* Result: SUCCEEDED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6f4da363-91c7-40db-bc2f-25c77a2bebbf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 0fa3b65809989575085a4616185042e1ac0c1744
* Result: FAILED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=93bc3bed-d845-4d6b-bfcc-340f56218589%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: a353cb93bfdf2e4637df536f7f077ef7e4abf03b
* Result: SUCCEEDED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d6cc1ee3-3587-42e1-ac69-214f4d260f42%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by georgebearden — APPROVED** [review]
looks good to me

**Pull request merged**
