### PR TITLE
fix(aws-apigateway-sqs): Remove /message path when delete method is not allowed

### PR DESCRIPTION
**Pull request by joe-king-sh**
*Issue #, if available:*
- #1029

*Description of changes:*

- Prevent the creation of the /message path when the DELETE method is not used, as this path is only utilized by the DELETE method.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 3de4b1f12d55313f564af43baf7f1e79acd3db7f
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1e144b58-2166-4471-946e-12907eeef78c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: fb9ec0f1bd00c2a33ffdf3bcfab4b6bc902ae939
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=97900a1a-bb84-484e-81c0-cc5ae24eb5e0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by biffgaut — APPROVED** [review]

**Comment by biffgaut** [comment]
Nice job, thanks!

**Comment by biffgaut** [comment]
This was published to npm, etc. with release 2.47.0

**Pull request merged**
