### PR TITLE
feat(aws-dynamodbstreams-pipes-stepfunctions):  new construct

### PR DESCRIPTION
**Pull request by biffgaut**

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 5080b5c0aa036f3ad923412262d06991032cffe0
* Result: SUCCEEDED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a167f3a2-3f58-426a-95a4-cd46c4b94e69%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 22baa22ad87742392a74970856d4a33de4ba2ce1
* Result: FAILED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=78797093-cae9-42c9-9479-3925d425ae95%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by georgebearden — APPROVED** [review]

**Review by georgebearden — APPROVED** [review]

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 0b953f7980432f55daa95407f3a49fce060b2902
* Result: FAILED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a0cbd3b0-e6f2-45e5-8d65-1bc9d4482260%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: a953c716aeda6ceb9a49ab4db9b32a995dcd7f01
* Result: SUCCEEDED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5ba71481-89b7-4e44-b3a8-0f951c1ee347%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: e5c6e066d1a55b0644063d2fab338a06da23d1cb
* Result: SUCCEEDED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=96e14819-b129-4262-bf11-89bd22a75ffd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by georgebearden — APPROVED** [review]

**Pull request merged**
