### PR TITLE
fix(aws-cloudfront-s3): observe props.logCloudFrontAccessLog

### LINKED ISSUE #1167: Use `jsii/superchain:1-bookworm-slim` for development
Use `jsii/superchain:1-bookworm-slim` for development

### Use Case

The projects currently uses `jsii/superchain:1-bullseye-slim` for development: https://github.com/awslabs/aws-solutions-constructs/blob/main/DEVELOPER_GUIDE.md#preparing-your-build-environment

As per their documentation in https://hub.docker.com/r/jsii/superchain, the `1-bullseye-slim` image is not actively maintained or updated.

### Proposed Solution

Switch to recommended `jsii/superchain:1-bookworm-slim` for development

### Other

The `jsii/superchain:1-bookworm-slim` uses latest version of node 18.x

```console
$ docker run -u root --rm --net=host -it -v $PWD:$PWD -w $PWD jsii/superchain:1-bookworm-slim
root@docker-desktop:/Users/trivikr/workspace/aws-solutions-constructs# node -v
v18.20.3
```

The `jsii/superchain:1-bullseye-slim` uses `node@v18.17.1`, as verified in https://github.com/awslabs/aws-solutions-constructs/pull/1166#issue-2440974816

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by biffgaut**
*Issue #, if available:*
Closes #1167 

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 002a3587e9f09150b6300e9bb63ffb11aab16edb
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=478107b6-17c7-4af1-a4d2-6aba7c3a2587%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: edc332383cbb83e9d4394fa0be3412a4490b7371
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ca53fe4a-71c3-43c1-b94a-91c44e74ecf2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 7e358d33ae820c888ea58b0e679b54003a1d2338
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=22bba0b5-8d1d-464b-a3f4-2f2dd3efd8a4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 1d328bb0065713131f36b185a40fe9a8a5301430
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a7355dd8-fab6-4e80-a36f-ff78f5c97cbe%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by georgebearden — APPROVED** [review]
Looks good to me

**Pull request merged**
