### PR TITLE
feat(aws-apigateway-dynamodb): add optional resourceName parameter

### LINKED ISSUE #848: ApiGatewayToDynamoDB: customize resource name on REST API
Hello, I would like to customize the generated resource name on my REST API when using `ApiGatewayToDynamoDB`.

### Use Case

Currently, the resource name is generated from the DynamoDB partition key 

https://github.com/awslabs/aws-solutions-constructs/blob/0bc9043be48b2ad635888e0359404e9b9dfc9337/source/patterns/%40aws-solutions-constructs/aws-apigateway-dynamodb/lib/index.ts#L152

However, I am trying to implement a more complex use case where my integration will query on the sort key. It feel weird to have to write:
```
readRequestTemplate: `{ \
  "TableName": "${dynamodbTable.tableName}", \
  "KeyConditionExpression": "PK = :v2 AND SK = :v1", \
  "ExpressionAttributeValues": { \
    ":v1": { \
      "S": "$input.params('PK')" \
    }, \
    ":v2": { \
      "S": "MY_VALUE" \
    } \
  } \
}`,
```

I understand that this is the default use case, but it should be customizable IMO.

### Proposed Solution

Add an optional `resourceName` string parameter on the construct and use it to define the resource name if it is passed. Otherwise, use the table's partition key like in the current implementation.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by fargito**
Fixes #848

*Description of changes:*
- Add a resourceName on the `ApiGatewayToDynamoDB` construct

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: e438583d0111c9192541e51eeb2059a499236d4c
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=db00fcff-6a86-44fc-8ae5-602fb58b9a79%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: a2f8e5b175d2c590e1989d8483f4b357915500d5
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c9218a39-937d-4922-a5c0-e56e65777075%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 416173b0c8805887c51bfd777445396d83473d2f
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=72cc372b-acd0-467d-b433-80d84d8a37bb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by biffgaut — CHANGES_REQUESTED** [review]
At least one of the integration tests is failing - 
```
@aws-solutions-constructs/aws-apigateway-dynamodb:  â”œâ”€ [~] AttributeDefinitions
@aws-solutions-constructs/aws-apigateway-dynamodb:  â”‚   â””â”€ @@ -1,6 +1,10 @@
@aws-solutions-constructs/aws-apigateway-dynamodb:  â”‚      [ ] [
@aws-solutions-constructs/aws-apigateway-dynamodb:  â”‚      [ ]   {
@aws-solutions-constructs/aws-apigateway-dynamodb:  â”‚      [-]     "AttributeName": "id",
@aws-solutions-constructs/aws-apigateway-dynamodb:  â”‚      [+]     "AttributeName": "PK",
@aws-solutions-constructs/aws-apigateway-dynamodb:  â”‚      [ ]     "AttributeType": "S"
@aws-solutions-constructs/aws-apigateway-dynamodb:  â”‚      [+]   },
@aws-solutions-constructs/aws-apigateway-dynamodb:  â”‚      [+]   {
@aws-solutions-constructs/aws-apigateway-dynamodb:  â”‚      [+]     "AttributeName": "SK",
@aws-solutions-constructs/aws-apigateway-dynamodb:  â”‚      [+]     "AttributeType": "S"
@aws-solutions-constructs/aws-apigateway-dynamodb:  â”‚      [ ]   }
@aws-solutions-constructs/aws-apigateway-dynamodb:  â”‚      [ ] ]
@aws-solutions-constructs/aws-apigateway-dynamodb:  â””â”€ [~] KeySchema (requires replacement)
@aws-solutions-constructs/aws-apigateway-dynamodb:      â””â”€ @@ -1,6 +1,10 @@
@aws-solutions-constructs/aws-apigateway-dynamodb:         [ ] [
@aws-solutions-constructs/aws-apigateway-dynamodb:         [ ]   {
@aws-solutions-constructs/aws-apigateway-dynamodb:         [-]     "AttributeName": "id",
@aws-solutions-constructs/aws-apigateway-dynamodb:         [+]     "AttributeName": "PK",
@aws-solutions-constructs/aws-apigateway-dynamodb:         [ ]     "KeyType": "HASH"
@aws-solutions-constructs/aws-apigateway-dynamodb:         [+]   },
@aws-solutions-constructs/aws-apigateway-dynamodb:         [+]   {
@aws-solutions-constructs/aws-apigateway-dynamodb:         [+]     "AttributeName": "SK",
@aws-solutions-constructs/aws-apigateway-dynamodb:         [+]     "KeyType": "RANGE"
@aws-solutions-constructs/aws-apigateway-dynamodb:         [ ]   }
@aws-solutions-constructs/aws-apigateway-dynamodb:         [ ] ]
@aws-solutions-constructs/aws-apigateway-dynamodb: Outputs
```
From a quick perusal, it looks like the PR changes the output for [integ.additional-request-templates.ts](https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/aws-apigateway-dynamodb/test/integ.additional-request-templates.ts).

**Comment by fargito** [comment]
I added an integration test, I'll check

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 1c847b42a8b21208f4e840aad2b93efdec72817f
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2131e3f4-1d51-497e-9197-d3aad69d1468%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: cf28cbd8d586d55cc754a3d0d75a68411eecaa29
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e4949baa-d18d-4544-b451-e279eb1f5667%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 4f8ad15327d1e8dab1bcc37cb2477eb1151e11a2
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=416cc74a-17bc-40c9-8f8d-8b8a10e1005b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 687ceff6ab1f8e39077eebc8baa23188ee7d0bef
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=202ae434-ba74-4bf7-84d8-b185e1ff28d7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by fargito** [comment]
Ok, I managed to get it working!

**Review by biffgaut — CHANGES_REQUESTED** [review]
Thanks for the submission! One thing to clear up - the initial issue we set out to fix was that the resourceName was tightly coupled to the partitionKey name. In this iteration they are still tightly coupled in the code for the readRequestTemplate at line 269, but now the partitionKeyName is assumed to be the same as the resourceName. Since the client must provide a partitionKeyName in the TableProps, this sets up a situation where a client could provide different values - which I think would lead to the read request not working as the partitionKeyName at line 281 would be incorrect.

We expected the readRequestTemplate to look like this:

```
      const readRequestTemplate = props.readRequestTemplate ??
        `{ \
          "TableName": "${this.dynamoTable.tableName}", \
          "KeyConditionExpression": "${partitionKeyName} = :v1", \
          "ExpressionAttributeValues": { \
            ":v1": { \
              "S": "$input.params('${resourceName}')" \
            } \
          } \
        }`;
```

That decouples the partitionKeyName and resourceName.

Integration test looks good, but we need an unit test or two to confirm the correctness of the Construct output (unit tests are in apigateway-dynamodb.test.ts)

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 7980c935b89ab08da8455e71f12528be429d167e
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2d2068b9-ca1d-45b9-9cff-dad11d82dc81%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by fargito** [comment]
@biffgaut you're absolutely right, I edited this, and also added a unit test

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: a794aa1fea57ddfcbe080bbe592414aad0348f1f
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a2c85ed9-5211-4f17-a782-309cb1184e63%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: aa078d4542b99c59a57b752bb029e0cf31b485c0
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=32687826-6989-4fab-b544-95941288b7b1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by biffgaut** [comment]
Looks like this is ready for review, but just want to confirm before diving in?

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 7f0b30346a9011301d6b3a56e3f0f4f55937f2cf
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d39d24fb-5dd0-4c78-9715-21ae58991a92%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by fargito** [comment]
That is correct @biffgaut 🙂

**Review by biffgaut — APPROVED** [review]

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: a4a959b6032ffd46e049f12df490731c530f7955
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e34bfe53-c92d-46c8-bb25-91562252365a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by biffgaut** [comment]
Great contribution - Thanks!

**Comment by biffgaut** [comment]
This will go out with the next release - since we just dropped a release yesterday the next one will probably in in the next week.

**Comment by fargito** [comment]
Thanks a lot! 🚀

**Pull request merged**
