### PR TITLE
feat(aws-kinesisstreams-lambda) Add existingStreamInterface to the Props object

### LINKED ISSUE #889: [aws-kinesisstreams-lambda]: Unable to use existing Kinesis Stream
### Reproduction Steps

```ts
// returns kinesis.IStream
const existingStreamObj = kinesis.Stream.fromStreamArn(this, 'stream', 'arn:aws:kinesis:ap-southeast-1:000000000000/stream/existing-stream');

new KinesisStreamsToLambda(this, 'job-kinesis-trigger', {
      existingLambdaObj,
      existingStreamObj, // wants kinesis.Stream
      kinesisEventSourceProps: {}
});
```

### Error Log

```
TS2740: Type 'IStream' is missing the following properties from type 'Stream': stream, parseEncryption, metricFromCannedFunction, physicalName, and 6 more.
```

### Environment

  - **CDK CLI Version      : 2.61.0**
  - **CDK Framework Version: 2.61.0**
  - **AWS Solutions Constructs Version     : 2.30.0**
  - **OS                   : macOS Ventura**
  - **Language             : Typescript**

### Other

Related issues: https://github.com/awslabs/aws-solutions-constructs/issues/58, https://github.com/awslabs/aws-solutions-constructs/pull/60

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by biffgaut**
*Issue #, if available:*
Closes #889 

*Description of changes:*
Allow clients to supply an IStream in addition to a Stream so the construct can use Streams that already exist in the account.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by georgebearden — DISMISSED** [review]
looks good to me

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: b475db069835cb06050f4139814ee03b1bd5fa23
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=98479a27-b69b-4ccf-84e4-227cb2be0c84%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 4e956b1f709540074d0a5ed5164bc2f0e96e2c7c
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a0cc2b51-0e97-4a09-936d-a6bea2a93695%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by biffgaut** [comment]
Cannot be implemented without a breaking change to the construct properties. See Issue #889

**Pull request closed without merging**
