### PR TITLE
feat(aws-cloudfront-apigateway-lambda): require explicit authentication type

### LINKED ISSUE #1043: feat(aws-cloudfront-apigateway-lambda): require explicit authentication type
Solutions Constructs default to following Best Practice advice, which for API Gateways is to not deploy unauthenticated APIs by default. Most API Gateway based constructs default to IAM authentication.

The combination of CloudFront and API Gateway does not support IAM authentication, so this construct [overrides the default IAM authentication type with NONE](https://github.com/awslabs/aws-solutions-constructs/blob/51ec028ebd4763965671483e74924e3b8e328337/source/patterns/%40aws-solutions-constructs/aws-cloudfront-apigateway-lambda/lib/index.ts#L127). A side effect of this is that if a client specifies IAM authentication in props it is silently overridden with NONE as well.

Implementing a different type of default authentication (CUSTOM, COGNITO) would required making too many assumptions about a client's use case, so this construct should be changed to not have an default authentication type - a client should be required to explicitly specify the desired authentication type.

This WILL BE a breaking change for existing clients using the default settings - these clients will have to update the construct props to include an explicit defaultMethodOptions value in the apiGatewayProps to maintain consistent behavior:

```
{
  apiGatewayProps: {
    defaultMethodOptions: {
      authorizationType: 'NONE'
    }
  }
}
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [x ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by biffgaut**
*Issue #, if available:*
Closes #1043

*Description of changes:*
Check incoming props to require explicit auth type
Update all integration tests from no auth to custom auth

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 7829fb39e9d9945f3656b573a7b73bdc168e8fe1
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7ba8dddc-584b-4d9a-aa07-3aff0f2b8c04%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: beb316e2882c04ce9de1a29b21d6567d31a5c8ab
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6db850c5-e8ca-4989-9b7e-67281c3e0c00%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 8ae588b9a21395c2f4891e8ef6ed94e33eab58f1
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9b3aa7ad-b1bf-4b6d-b2be-726bc76db0f5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by georgebearden — APPROVED** [review]
looks good to me

**Pull request merged**
