### PR TITLE
feat(aws-apigateway-sqs): add schema validation for create operation

### LINKED ISSUE #1215: ApiGatewayToSqs : add schema validation for create operation
It would be helpful to have schema validation made directly on the API Gateway when we do a creation operation.

### PR DESCRIPTION
**Pull request by biffgaut**
*Issue #, if available:*
Closes #1215

*Description of changes:*
Accept a set of JsonSchema that API Gateway will enforce on create calls (e.g. - confirms the format of the SQS message at the API level)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 8d0b2b8fecb5d2fc7a2903228f8ff957405fefa1
* Result: SUCCEEDED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=dd27a9a6-1382-4fa6-8e8b-5d76ef0237c7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: d623e324af36ed01d97f314bcec05b94b55c2aea
* Result: FAILED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9b08555d-f78a-423d-9fa7-dd3122e5cdcf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: a0ea38f97c2b599dad8b77f38ac2063c1af30841
* Result: SUCCEEDED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2fab687c-fd23-4723-ad04-2664b6c28ade%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by georgebearden — APPROVED** [review]
looks good to me - one minor comment on the README.

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 13a77b8748cb1e6c3b402f4dad08f6fb37cf4f9e
* Result: SUCCEEDED
* [Build Logs](https://ab0is2wdo4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=16d1fe08-3d14-4926-8d4d-0459a3ba4485%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by georgebearden — APPROVED** [review]
looks good to me

**Pull request merged**
