### PR TITLE
fix(release): re-sync Release and Main

### PR DESCRIPTION
**Pull request by biffgaut**
* feat(aws-fargate-dynamodb): create new construct (#633)

* created README for aws-fargate-dynamodb

* created aws-fargate-dynamodb construct

* revised buildDynamoDBTable helper function to support old/new constructs

* updated prop variable name

* added error and endpoint checking tests

* checked for table permissions

* checked props in input-validation

* moved table interface and object check to buildDynamoDBTable function

* created prop check function in dynamo helper file

* chore(release): 1.150.0

* chore(changelog): Updated CHANGELOG.md

* CDK version driven changes

* Align CDK version

* Sync CDk Versions

* Sync CDK versions

Co-authored-by: biffgaut <78155736+biffgaut@users.noreply.github.com>
Co-authored-by: mickychetta <45010053+mickychetta@users.noreply.github.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: a22694b89f69638582dba055841d5492b2f5cceb
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=aedd1f37-655a-446c-a3d9-9ed57bf6c7d8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: a22694b89f69638582dba055841d5492b2f5cceb
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=23f0a346-0314-44b8-9488-43c4b4edad9a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by biffgaut** [comment]
main and release appeared to have the same code after 1.150.0, but showed as being in conflict. Went ahead and merged them on the weekend with no on available to review.

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: f8c0554fae921bea597eef6f9a60ae1a19111f95
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e21150df-ae19-4fd1-81f5-78d3df116567%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: f8c0554fae921bea597eef6f9a60ae1a19111f95
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cdbbf3e0-18c8-42e5-a01d-8e75a4ec6027%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
